# SPDX-License-Identifier: AGPL-3.0-only

from collections.abc import Callable

type EventCallback = Callable[..., object]

class RTCSessionDescription:
    sdp: str
    type: str
    def __init__(self, *, sdp: str, type: str) -> None: ...

class RTCDataChannel:
    @property
    def readyState(self) -> str: ...
    def on(self, event: str, callback: EventCallback) -> EventCallback: ...
    def send(self, data: bytes | str) -> None: ...
    def close(self) -> None: ...

class RTCPeerConnection:
    def __init__(self) -> None: ...
    @property
    def connectionState(self) -> str: ...
    @property
    def localDescription(self) -> RTCSessionDescription: ...
    def createDataChannel(
        self,
        label: str,
        maxPacketLifeTime: int | None = ...,
        maxRetransmits: int | None = ...,
        ordered: bool = ...,
        protocol: str = ...,
        negotiated: bool = ...,
        id: int | None = ...,
    ) -> RTCDataChannel: ...
    async def createOffer(self) -> RTCSessionDescription: ...
    async def setLocalDescription(self, sessionDescription: RTCSessionDescription) -> None: ...
    async def setRemoteDescription(self, sessionDescription: RTCSessionDescription) -> None: ...
    async def close(self) -> None: ...
    def on(self, event: str, callback: EventCallback) -> EventCallback: ...
