[package]
name = "onvif"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>"]
edition = "2024"
license = "MIT"

[package.metadata.cargo-machete]
ignored = ["xml-rs"]

[lints]
workspace = true

[dependencies]
base64 = "0.23"
chrono = "0.4"
digest_auth = "0.3"
nonzero_ext = "0.3"
schema = { path = "../schema", features = [
  "analytics",
  "devicemgmt",
  "event",
  "imaging",
  "media",
  "media2",
  "ptz",
  "recording",
  "replay",
  "schedule",
  "search",
] }
sha1 = "0.11"
thiserror = "2.0"
tracing = "0.1"
ureq = { version = "3", default-features = false, features = ["native-tls"] }
url = "2"
uuid = { version = "1", features = ["v4"] }
xml-rs = "1.0.0"
xmltree = "0.12"
xsd-types = { path = "../xsd-types" }
yaserde = "0.12"
yaserde_derive = "0.12"

[dev-dependencies]
b_2 = { path = "../wsdl_rs/b_2" }
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
tracing-subscriber = "0.3"
