[package]
name = "search"
version = "0.1.0"
edition = "2024"
license = "MIT"

[package.metadata.cargo-machete]
ignored = ["yaserde"]

[lints]
workspace = true

[dependencies]
onvif = { package = "onvif-xsd", path = "../../xsd_rs/onvif_xsd" }
transport = { path = "../../transport" }
validate = { path = "../../validate" }
xsd-types = { path = "../../xsd-types" }
yaserde = "0.12"
yaserde_derive = "0.12"
