[package]
name = "onvif-xsd"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
b_2 = { path = "../../wsdl_rs/b_2" }
common = { path = "../../xsd_rs/common" }
soap_envelope = { path = "../../xsd_rs/soap_envelope" }
validate = { path = "../../validate" }
xml-rs = "0.8"
xmlmime = { path = "../../xsd_rs/xmlmime" }
xop = { path = "../../xsd_rs/xop" }
xsd-macro-utils = { path = "../../xsd-macro-utils" }
xsd-types = { path = "../../xsd-types" }
yaserde = "0.12"
yaserde_derive = "0.12"
