[package]
name = "reo-proto"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
authors = ["xnorpx <xnorpx@outlook.com>"]

[package.metadata.cargo-machete]
ignored = ["md-5", "xml-rs"]

[lints]
workspace = true

[dependencies]
md-5 = "0.11"
aes = "0.9"
cfb-mode = "0.9"
cipher = "0.5"
crc32fast = "1"
arrayvec = "0.7"
xml-rs = "1.0"
tracing = "0.1"

[dev-dependencies]
hex-literal = "1.1"
