[package]
name = "display"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
common = { path = "../../xsd_rs/common" }
onvif = { package = "onvif-xsd", path = "../../xsd_rs/onvif_xsd" }
transport = { path = "../../transport" }
validate = { path = "../../validate" }
xml-rs = "0.8.29"
xsd-macro-utils = { path = "../../xsd-macro-utils" }
xsd-types = { path = "../../xsd-types" }
yaserde = "0.12"
yaserde_derive = "0.12"
