[package]
name = "bf_2"
version = "0.1.0"
edition = "2024"
license = "MIT"

[package.metadata.cargo-machete]
ignored = ["yaserde"]

[lints]
workspace = true

[dependencies]
validate = { path = "../../validate" }
xsd-types = { path = "../../xsd-types" }
yaserde = "0.12"
yaserde_derive = "0.12"
ws_addr = { path = "../../wsdl_rs/ws_addr" }
xml_xsd = { path = "../../wsdl_rs/xml_xsd" }
